//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amplitude.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amplitude.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        internal static string AccentColorLabel {
            get {
                return ResourceManager.GetString("AccentColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        internal static string AddClipToQueue {
            get {
                return ResourceManager.GetString("AddClipToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add output device.
        /// </summary>
        internal static string AddSoundClipOutput {
            get {
                return ResourceManager.GetString("AddSoundClipOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scale tiles to fit window.
        /// </summary>
        internal static string AutoScaleTilesToWindowLabel {
            get {
                return ResourceManager.GetString("AutoScaleTilesToWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow tiles to be stretched to fill available window space, or set a custom tile size.
        /// </summary>
        internal static string AutoScaleTilesToWindowTooltip {
            get {
                return ResourceManager.GetString("AutoScaleTilesToWindowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache audio which requires resampling to speed up playback at the cost of RAM.
        /// </summary>
        internal static string CacheAudioExplanation {
            get {
                return ResourceManager.GetString("CacheAudioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache resampled audio.
        /// </summary>
        internal static string CacheAudioLabel {
            get {
                return ResourceManager.GetString("CacheAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear audio cache to free RAM.
        /// </summary>
        internal static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset window sizes and positions.
        /// </summary>
        internal static string ClearPositions {
            get {
                return ResourceManager.GetString("ClearPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case a window is out of reach, reset window sizes and positions.
        /// </summary>
        internal static string ClearPositionsTooltip {
            get {
                return ResourceManager.GetString("ClearPositionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear tile.
        /// </summary>
        internal static string ClearTile {
            get {
                return ResourceManager.GetString("ClearTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound clip file path.
        /// </summary>
        internal static string ClipAudioFilePathLabel {
            get {
                return ResourceManager.GetString("ClipAudioFilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file path....
        /// </summary>
        internal static string ClipFilePathPlaceholder {
            get {
                return ResourceManager.GetString("ClipFilePathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        internal static string ClipHotkeyLabel {
            get {
                return ResourceManager.GetString("ClipHotkeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image file path.
        /// </summary>
        internal static string ClipImageFilePathLabel {
            get {
                return ResourceManager.GetString("ClipImageFilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip name.
        /// </summary>
        internal static string ClipNameLabel {
            get {
                return ResourceManager.GetString("ClipNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name....
        /// </summary>
        internal static string ClipNamePlaceholder {
            get {
                return ResourceManager.GetString("ClipNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string ColumnsPlaceholder {
            get {
                return ResourceManager.GetString("ColumnsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new clip here.
        /// </summary>
        internal static string CreateClipInPlace {
            get {
                return ResourceManager.GetString("CreateClipInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomTheme {
            get {
                return ResourceManager.GetString("CustomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteSoundClipButton {
            get {
                return ResourceManager.GetString("DeleteSoundClipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Sound Clip &quot;{0}&quot;?.
        /// </summary>
        internal static string DeleteSoundClipConfirmationPrompt {
            get {
                return ResourceManager.GetString("DeleteSoundClipConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        internal static string DeleteSoundClipConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteSoundClipConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string DismissWindow {
            get {
                return ResourceManager.GetString("DismissWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Output Profile.
        /// </summary>
        internal static string EditOutputProfileTitle {
            get {
                return ResourceManager.GetString("EditOutputProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit output profile.
        /// </summary>
        internal static string EditOutputProfileTooltip {
            get {
                return ResourceManager.GetString("EditOutputProfileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sound Clip.
        /// </summary>
        internal static string EditSoundClipTitle {
            get {
                return ResourceManager.GetString("EditSoundClipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sound clip.
        /// </summary>
        internal static string EditSoundClipTooltip {
            get {
                return ResourceManager.GetString("EditSoundClipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a Sound Clip here to bind it!.
        /// </summary>
        internal static string EmptyTilePrompt {
            get {
                return ResourceManager.GetString("EmptyTilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        internal static string ErrorListTitle {
            get {
                return ResourceManager.GetString("ErrorListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet available on your platform.
        /// </summary>
        internal static string FeatureUnavailable {
            get {
                return ResourceManager.GetString("FeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file is an unrecognized format: &quot;{0}&quot;.
        /// </summary>
        internal static string FileBadFormatString {
            get {
                return ResourceManager.GetString("FileBadFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an audio file....
        /// </summary>
        internal static string FileBrowseAudio {
            get {
                return ResourceManager.GetString("FileBrowseAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image file....
        /// </summary>
        internal static string FileBrowseImage {
            get {
                return ResourceManager.GetString("FileBrowseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file cannot be found: &quot;{0}&quot;.
        /// </summary>
        internal static string FileMissingString {
            get {
                return ResourceManager.GetString("FileMissingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path....
        /// </summary>
        internal static string FilePathPlaceholder {
            get {
                return ResourceManager.GetString("FilePathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global output settings.
        /// </summary>
        internal static string GlobalOutputDefaults {
            get {
                return ResourceManager.GetString("GlobalOutputDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string GlobalSettingsTitle {
            get {
                return ResourceManager.GetString("GlobalSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        internal static string GridSizeLabel {
            get {
                return ResourceManager.GetString("GridSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid tiles size.
        /// </summary>
        internal static string GridTileSizeLabel {
            get {
                return ResourceManager.GetString("GridTileSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy a Sound Clip from the Sound Clip List and paste it into any Grid Tile using right click!.
        /// </summary>
        internal static string GridTutorial {
            get {
                return ResourceManager.GetString("GridTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string HeightPlaceholder {
            get {
                return ResourceManager.GetString("HeightPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide tutorial.
        /// </summary>
        internal static string HideTutorial {
            get {
                return ResourceManager.GetString("HideTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ESC to clear this binding....
        /// </summary>
        internal static string HotkeyCancelPlaceholder {
            get {
                return ResourceManager.GetString("HotkeyCancelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record a key combination....
        /// </summary>
        internal static string HotkeyPlaceholder {
            get {
                return ResourceManager.GetString("HotkeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected theme is out of range: {0}.
        /// </summary>
        internal static string InvalidThemeError {
            get {
                return ResourceManager.GetString("InvalidThemeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat clip.
        /// </summary>
        internal static string LoopClipLabel {
            get {
                return ResourceManager.GetString("LoopClipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat clip forever.
        /// </summary>
        internal static string LoopClipTooltip {
            get {
                return ResourceManager.GetString("LoopClipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master volume.
        /// </summary>
        internal static string MasterVolumeLabel {
            get {
                return ResourceManager.GetString("MasterVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output device &quot;{0}&quot; is missing and cannot be used for playback!.
        /// </summary>
        internal static string MissingDeviceString {
            get {
                return ResourceManager.GetString("MissingDeviceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Output Profile &quot;{0}&quot; is missing and cannot be used for playback!.
        /// </summary>
        internal static string MissingOutputProfileString {
            get {
                return ResourceManager.GetString("MissingOutputProfileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new output profile.
        /// </summary>
        internal static string NewOutputProfileTooltip {
            get {
                return ResourceManager.GetString("NewOutputProfileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sound clip.
        /// </summary>
        internal static string NewSoundClip {
            get {
                return ResourceManager.GetString("NewSoundClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version available.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} can be downloaded from the releases page on GitHub.
        /// </summary>
        internal static string NewVersionCanBeDownloaded {
            get {
                return ResourceManager.GetString("NewVersionCanBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} can be installed now.
        /// </summary>
        internal static string NewVersionCanBeInstalled {
            get {
                return ResourceManager.GetString("NewVersionCanBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string NoticeLabel {
            get {
                return ResourceManager.GetString("NoticeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure theme.
        /// </summary>
        internal static string OpenThemeSettingsButton {
            get {
                return ResourceManager.GetString("OpenThemeSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output device.
        /// </summary>
        internal static string OutputDeviceLabel {
            get {
                return ResourceManager.GetString("OutputDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Output Profile &quot;{0}&quot; has errors:\\n{1}.
        /// </summary>
        internal static string OutputProfileError {
            get {
                return ResourceManager.GetString("OutputProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Profile.
        /// </summary>
        internal static string OutputProfileLabel {
            get {
                return ResourceManager.GetString("OutputProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output profile name.
        /// </summary>
        internal static string OutputProfileNameLabel {
            get {
                return ResourceManager.GetString("OutputProfileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output volume.
        /// </summary>
        internal static string OutputVolumeLabel {
            get {
                return ResourceManager.GetString("OutputVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste clip to tile.
        /// </summary>
        internal static string PasteClip {
            get {
                return ResourceManager.GetString("PasteClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play audio.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache all audio files which may need resampling at application startup.
        /// </summary>
        internal static string PreCacheAudioExplanation {
            get {
                return ResourceManager.GetString("PreCacheAudioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precache audio at startup.
        /// </summary>
        internal static string PreCacheAudioLabel {
            get {
                return ResourceManager.GetString("PreCacheAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove output device.
        /// </summary>
        internal static string RemoveSoundClipOutput {
            get {
                return ResourceManager.GetString("RemoveSoundClipOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resampling audio.
        /// </summary>
        internal static string ResamplingAudioTooltip {
            get {
                return ResourceManager.GetString("ResamplingAudioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset theme settings.
        /// </summary>
        internal static string ResetThemeBaseTooltip {
            get {
                return ResourceManager.GetString("ResetThemeBaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string RowsPlaceholder {
            get {
                return ResourceManager.GetString("RowsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Sound Clip name.
        /// </summary>
        internal static string SaveButtonDisabledTooltip {
            get {
                return ResourceManager.GetString("SaveButtonDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary color.
        /// </summary>
        internal static string SecondaryColorLabel {
            get {
                return ResourceManager.GetString("SecondaryColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show name in grid tile view.
        /// </summary>
        internal static string ShowNameOnGridTile {
            get {
                return ResourceManager.GetString("ShowNameOnGridTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sound Clip &quot;{0}&quot; has errors:\\n{1}.
        /// </summary>
        internal static string SoundClipError {
            get {
                return ResourceManager.GetString("SoundClipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SoundClipListSearch {
            get {
                return ResourceManager.GetString("SoundClipListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Clip List.
        /// </summary>
        internal static string SoundClipListTitle {
            get {
                return ResourceManager.GetString("SoundClipListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop audio.
        /// </summary>
        internal static string StopAllAudio {
            get {
                return ResourceManager.GetString("StopAllAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all audio hotkey.
        /// </summary>
        internal static string StopAllAudioHotkeyLabel {
            get {
                return ResourceManager.GetString("StopAllAudioHotkeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle audio when triggered repeatedly.
        /// </summary>
        internal static string StopAudioOnRetrigger {
            get {
                return ResourceManager.GetString("StopAudioOnRetrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop previous audio from playing.
        /// </summary>
        internal static string StopPreviousAudioTrack {
            get {
                return ResourceManager.GetString("StopPreviousAudioTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test audio.
        /// </summary>
        internal static string TestSound {
            get {
                return ResourceManager.GetString("TestSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base theme.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Settings.
        /// </summary>
        internal static string ThemeSettingsTitle {
            get {
                return ResourceManager.GetString("ThemeSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdatePromptTitle {
            get {
                return ResourceManager.GetString("UpdatePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View releases.
        /// </summary>
        internal static string ViewReleases {
            get {
                return ResourceManager.GetString("ViewReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string VolumeLabel {
            get {
                return ResourceManager.GetString("VolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string WidthPlaceholder {
            get {
                return ResourceManager.GetString("WidthPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window background color.
        /// </summary>
        internal static string WindowBackgroundColorLabel {
            get {
                return ResourceManager.GetString("WindowBackgroundColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window background opacity.
        /// </summary>
        internal static string WindowBackgroundOpacityLabel {
            get {
                return ResourceManager.GetString("WindowBackgroundOpacityLabel", resourceCulture);
            }
        }
    }
}
